// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: uartmessage.proto

package de.fhffm.ssns.messaging;

public final class UARTMessageProtos {
  private UARTMessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UARTMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .UARTMessage.Type type = 1;
    /**
     * <code>required .UARTMessage.Type type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .UARTMessage.Type type = 1;</code>
     */
    de.fhffm.ssns.messaging.UARTMessageProtos.UARTMessage.Type getType();

    // optional .Beacon beacon = 2;
    /**
     * <code>optional .Beacon beacon = 2;</code>
     */
    boolean hasBeacon();
    /**
     * <code>optional .Beacon beacon = 2;</code>
     */
    de.fhffm.ssns.messaging.UARTMessageProtos.Beacon getBeacon();
    /**
     * <code>optional .Beacon beacon = 2;</code>
     */
    de.fhffm.ssns.messaging.UARTMessageProtos.BeaconOrBuilder getBeaconOrBuilder();

    // optional .Service service = 3;
    /**
     * <code>optional .Service service = 3;</code>
     */
    boolean hasService();
    /**
     * <code>optional .Service service = 3;</code>
     */
    de.fhffm.ssns.messaging.UARTMessageProtos.Service getService();
    /**
     * <code>optional .Service service = 3;</code>
     */
    de.fhffm.ssns.messaging.UARTMessageProtos.ServiceOrBuilder getServiceOrBuilder();
  }
  /**
   * Protobuf type {@code UARTMessage}
   */
  public static final class UARTMessage extends
      com.google.protobuf.GeneratedMessage
      implements UARTMessageOrBuilder {
    // Use UARTMessage.newBuilder() to construct.
    private UARTMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private UARTMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final UARTMessage defaultInstance;
    public static UARTMessage getDefaultInstance() {
      return defaultInstance;
    }

    public UARTMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private UARTMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              de.fhffm.ssns.messaging.UARTMessageProtos.UARTMessage.Type value = de.fhffm.ssns.messaging.UARTMessageProtos.UARTMessage.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              de.fhffm.ssns.messaging.UARTMessageProtos.Beacon.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = beacon_.toBuilder();
              }
              beacon_ = input.readMessage(de.fhffm.ssns.messaging.UARTMessageProtos.Beacon.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(beacon_);
                beacon_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              de.fhffm.ssns.messaging.UARTMessageProtos.Service.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = service_.toBuilder();
              }
              service_ = input.readMessage(de.fhffm.ssns.messaging.UARTMessageProtos.Service.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(service_);
                service_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.fhffm.ssns.messaging.UARTMessageProtos.internal_static_UARTMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.fhffm.ssns.messaging.UARTMessageProtos.internal_static_UARTMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.fhffm.ssns.messaging.UARTMessageProtos.UARTMessage.class, de.fhffm.ssns.messaging.UARTMessageProtos.UARTMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<UARTMessage> PARSER =
        new com.google.protobuf.AbstractParser<UARTMessage>() {
      public UARTMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UARTMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<UARTMessage> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code UARTMessage.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SERVICE = 1;</code>
       */
      SERVICE(0, 1),
      /**
       * <code>BEACON = 2;</code>
       */
      BEACON(1, 2),
      ;

      /**
       * <code>SERVICE = 1;</code>
       */
      public static final int SERVICE_VALUE = 1;
      /**
       * <code>BEACON = 2;</code>
       */
      public static final int BEACON_VALUE = 2;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 1: return SERVICE;
          case 2: return BEACON;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return de.fhffm.ssns.messaging.UARTMessageProtos.UARTMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:UARTMessage.Type)
    }

    private int bitField0_;
    // required .UARTMessage.Type type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private de.fhffm.ssns.messaging.UARTMessageProtos.UARTMessage.Type type_;
    /**
     * <code>required .UARTMessage.Type type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .UARTMessage.Type type = 1;</code>
     */
    public de.fhffm.ssns.messaging.UARTMessageProtos.UARTMessage.Type getType() {
      return type_;
    }

    // optional .Beacon beacon = 2;
    public static final int BEACON_FIELD_NUMBER = 2;
    private de.fhffm.ssns.messaging.UARTMessageProtos.Beacon beacon_;
    /**
     * <code>optional .Beacon beacon = 2;</code>
     */
    public boolean hasBeacon() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .Beacon beacon = 2;</code>
     */
    public de.fhffm.ssns.messaging.UARTMessageProtos.Beacon getBeacon() {
      return beacon_;
    }
    /**
     * <code>optional .Beacon beacon = 2;</code>
     */
    public de.fhffm.ssns.messaging.UARTMessageProtos.BeaconOrBuilder getBeaconOrBuilder() {
      return beacon_;
    }

    // optional .Service service = 3;
    public static final int SERVICE_FIELD_NUMBER = 3;
    private de.fhffm.ssns.messaging.UARTMessageProtos.Service service_;
    /**
     * <code>optional .Service service = 3;</code>
     */
    public boolean hasService() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .Service service = 3;</code>
     */
    public de.fhffm.ssns.messaging.UARTMessageProtos.Service getService() {
      return service_;
    }
    /**
     * <code>optional .Service service = 3;</code>
     */
    public de.fhffm.ssns.messaging.UARTMessageProtos.ServiceOrBuilder getServiceOrBuilder() {
      return service_;
    }

    private void initFields() {
      type_ = de.fhffm.ssns.messaging.UARTMessageProtos.UARTMessage.Type.SERVICE;
      beacon_ = de.fhffm.ssns.messaging.UARTMessageProtos.Beacon.getDefaultInstance();
      service_ = de.fhffm.ssns.messaging.UARTMessageProtos.Service.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasBeacon()) {
        if (!getBeacon().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasService()) {
        if (!getService().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, beacon_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, service_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, beacon_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, service_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static de.fhffm.ssns.messaging.UARTMessageProtos.UARTMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.fhffm.ssns.messaging.UARTMessageProtos.UARTMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.fhffm.ssns.messaging.UARTMessageProtos.UARTMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.fhffm.ssns.messaging.UARTMessageProtos.UARTMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.fhffm.ssns.messaging.UARTMessageProtos.UARTMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.fhffm.ssns.messaging.UARTMessageProtos.UARTMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static de.fhffm.ssns.messaging.UARTMessageProtos.UARTMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static de.fhffm.ssns.messaging.UARTMessageProtos.UARTMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static de.fhffm.ssns.messaging.UARTMessageProtos.UARTMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.fhffm.ssns.messaging.UARTMessageProtos.UARTMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.fhffm.ssns.messaging.UARTMessageProtos.UARTMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UARTMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements de.fhffm.ssns.messaging.UARTMessageProtos.UARTMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.fhffm.ssns.messaging.UARTMessageProtos.internal_static_UARTMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.fhffm.ssns.messaging.UARTMessageProtos.internal_static_UARTMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.fhffm.ssns.messaging.UARTMessageProtos.UARTMessage.class, de.fhffm.ssns.messaging.UARTMessageProtos.UARTMessage.Builder.class);
      }

      // Construct using de.fhffm.ssns.messaging.UARTMessageProtos.UARTMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getBeaconFieldBuilder();
          getServiceFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = de.fhffm.ssns.messaging.UARTMessageProtos.UARTMessage.Type.SERVICE;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (beaconBuilder_ == null) {
          beacon_ = de.fhffm.ssns.messaging.UARTMessageProtos.Beacon.getDefaultInstance();
        } else {
          beaconBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (serviceBuilder_ == null) {
          service_ = de.fhffm.ssns.messaging.UARTMessageProtos.Service.getDefaultInstance();
        } else {
          serviceBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.fhffm.ssns.messaging.UARTMessageProtos.internal_static_UARTMessage_descriptor;
      }

      public de.fhffm.ssns.messaging.UARTMessageProtos.UARTMessage getDefaultInstanceForType() {
        return de.fhffm.ssns.messaging.UARTMessageProtos.UARTMessage.getDefaultInstance();
      }

      public de.fhffm.ssns.messaging.UARTMessageProtos.UARTMessage build() {
        de.fhffm.ssns.messaging.UARTMessageProtos.UARTMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.fhffm.ssns.messaging.UARTMessageProtos.UARTMessage buildPartial() {
        de.fhffm.ssns.messaging.UARTMessageProtos.UARTMessage result = new de.fhffm.ssns.messaging.UARTMessageProtos.UARTMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (beaconBuilder_ == null) {
          result.beacon_ = beacon_;
        } else {
          result.beacon_ = beaconBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (serviceBuilder_ == null) {
          result.service_ = service_;
        } else {
          result.service_ = serviceBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.fhffm.ssns.messaging.UARTMessageProtos.UARTMessage) {
          return mergeFrom((de.fhffm.ssns.messaging.UARTMessageProtos.UARTMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.fhffm.ssns.messaging.UARTMessageProtos.UARTMessage other) {
        if (other == de.fhffm.ssns.messaging.UARTMessageProtos.UARTMessage.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasBeacon()) {
          mergeBeacon(other.getBeacon());
        }
        if (other.hasService()) {
          mergeService(other.getService());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (hasBeacon()) {
          if (!getBeacon().isInitialized()) {
            
            return false;
          }
        }
        if (hasService()) {
          if (!getService().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.fhffm.ssns.messaging.UARTMessageProtos.UARTMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.fhffm.ssns.messaging.UARTMessageProtos.UARTMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .UARTMessage.Type type = 1;
      private de.fhffm.ssns.messaging.UARTMessageProtos.UARTMessage.Type type_ = de.fhffm.ssns.messaging.UARTMessageProtos.UARTMessage.Type.SERVICE;
      /**
       * <code>required .UARTMessage.Type type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .UARTMessage.Type type = 1;</code>
       */
      public de.fhffm.ssns.messaging.UARTMessageProtos.UARTMessage.Type getType() {
        return type_;
      }
      /**
       * <code>required .UARTMessage.Type type = 1;</code>
       */
      public Builder setType(de.fhffm.ssns.messaging.UARTMessageProtos.UARTMessage.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .UARTMessage.Type type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = de.fhffm.ssns.messaging.UARTMessageProtos.UARTMessage.Type.SERVICE;
        onChanged();
        return this;
      }

      // optional .Beacon beacon = 2;
      private de.fhffm.ssns.messaging.UARTMessageProtos.Beacon beacon_ = de.fhffm.ssns.messaging.UARTMessageProtos.Beacon.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          de.fhffm.ssns.messaging.UARTMessageProtos.Beacon, de.fhffm.ssns.messaging.UARTMessageProtos.Beacon.Builder, de.fhffm.ssns.messaging.UARTMessageProtos.BeaconOrBuilder> beaconBuilder_;
      /**
       * <code>optional .Beacon beacon = 2;</code>
       */
      public boolean hasBeacon() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .Beacon beacon = 2;</code>
       */
      public de.fhffm.ssns.messaging.UARTMessageProtos.Beacon getBeacon() {
        if (beaconBuilder_ == null) {
          return beacon_;
        } else {
          return beaconBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Beacon beacon = 2;</code>
       */
      public Builder setBeacon(de.fhffm.ssns.messaging.UARTMessageProtos.Beacon value) {
        if (beaconBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          beacon_ = value;
          onChanged();
        } else {
          beaconBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Beacon beacon = 2;</code>
       */
      public Builder setBeacon(
          de.fhffm.ssns.messaging.UARTMessageProtos.Beacon.Builder builderForValue) {
        if (beaconBuilder_ == null) {
          beacon_ = builderForValue.build();
          onChanged();
        } else {
          beaconBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Beacon beacon = 2;</code>
       */
      public Builder mergeBeacon(de.fhffm.ssns.messaging.UARTMessageProtos.Beacon value) {
        if (beaconBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              beacon_ != de.fhffm.ssns.messaging.UARTMessageProtos.Beacon.getDefaultInstance()) {
            beacon_ =
              de.fhffm.ssns.messaging.UARTMessageProtos.Beacon.newBuilder(beacon_).mergeFrom(value).buildPartial();
          } else {
            beacon_ = value;
          }
          onChanged();
        } else {
          beaconBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Beacon beacon = 2;</code>
       */
      public Builder clearBeacon() {
        if (beaconBuilder_ == null) {
          beacon_ = de.fhffm.ssns.messaging.UARTMessageProtos.Beacon.getDefaultInstance();
          onChanged();
        } else {
          beaconBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .Beacon beacon = 2;</code>
       */
      public de.fhffm.ssns.messaging.UARTMessageProtos.Beacon.Builder getBeaconBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getBeaconFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Beacon beacon = 2;</code>
       */
      public de.fhffm.ssns.messaging.UARTMessageProtos.BeaconOrBuilder getBeaconOrBuilder() {
        if (beaconBuilder_ != null) {
          return beaconBuilder_.getMessageOrBuilder();
        } else {
          return beacon_;
        }
      }
      /**
       * <code>optional .Beacon beacon = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          de.fhffm.ssns.messaging.UARTMessageProtos.Beacon, de.fhffm.ssns.messaging.UARTMessageProtos.Beacon.Builder, de.fhffm.ssns.messaging.UARTMessageProtos.BeaconOrBuilder> 
          getBeaconFieldBuilder() {
        if (beaconBuilder_ == null) {
          beaconBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              de.fhffm.ssns.messaging.UARTMessageProtos.Beacon, de.fhffm.ssns.messaging.UARTMessageProtos.Beacon.Builder, de.fhffm.ssns.messaging.UARTMessageProtos.BeaconOrBuilder>(
                  beacon_,
                  getParentForChildren(),
                  isClean());
          beacon_ = null;
        }
        return beaconBuilder_;
      }

      // optional .Service service = 3;
      private de.fhffm.ssns.messaging.UARTMessageProtos.Service service_ = de.fhffm.ssns.messaging.UARTMessageProtos.Service.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          de.fhffm.ssns.messaging.UARTMessageProtos.Service, de.fhffm.ssns.messaging.UARTMessageProtos.Service.Builder, de.fhffm.ssns.messaging.UARTMessageProtos.ServiceOrBuilder> serviceBuilder_;
      /**
       * <code>optional .Service service = 3;</code>
       */
      public boolean hasService() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .Service service = 3;</code>
       */
      public de.fhffm.ssns.messaging.UARTMessageProtos.Service getService() {
        if (serviceBuilder_ == null) {
          return service_;
        } else {
          return serviceBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Service service = 3;</code>
       */
      public Builder setService(de.fhffm.ssns.messaging.UARTMessageProtos.Service value) {
        if (serviceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          service_ = value;
          onChanged();
        } else {
          serviceBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Service service = 3;</code>
       */
      public Builder setService(
          de.fhffm.ssns.messaging.UARTMessageProtos.Service.Builder builderForValue) {
        if (serviceBuilder_ == null) {
          service_ = builderForValue.build();
          onChanged();
        } else {
          serviceBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Service service = 3;</code>
       */
      public Builder mergeService(de.fhffm.ssns.messaging.UARTMessageProtos.Service value) {
        if (serviceBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              service_ != de.fhffm.ssns.messaging.UARTMessageProtos.Service.getDefaultInstance()) {
            service_ =
              de.fhffm.ssns.messaging.UARTMessageProtos.Service.newBuilder(service_).mergeFrom(value).buildPartial();
          } else {
            service_ = value;
          }
          onChanged();
        } else {
          serviceBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Service service = 3;</code>
       */
      public Builder clearService() {
        if (serviceBuilder_ == null) {
          service_ = de.fhffm.ssns.messaging.UARTMessageProtos.Service.getDefaultInstance();
          onChanged();
        } else {
          serviceBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .Service service = 3;</code>
       */
      public de.fhffm.ssns.messaging.UARTMessageProtos.Service.Builder getServiceBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getServiceFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Service service = 3;</code>
       */
      public de.fhffm.ssns.messaging.UARTMessageProtos.ServiceOrBuilder getServiceOrBuilder() {
        if (serviceBuilder_ != null) {
          return serviceBuilder_.getMessageOrBuilder();
        } else {
          return service_;
        }
      }
      /**
       * <code>optional .Service service = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          de.fhffm.ssns.messaging.UARTMessageProtos.Service, de.fhffm.ssns.messaging.UARTMessageProtos.Service.Builder, de.fhffm.ssns.messaging.UARTMessageProtos.ServiceOrBuilder> 
          getServiceFieldBuilder() {
        if (serviceBuilder_ == null) {
          serviceBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              de.fhffm.ssns.messaging.UARTMessageProtos.Service, de.fhffm.ssns.messaging.UARTMessageProtos.Service.Builder, de.fhffm.ssns.messaging.UARTMessageProtos.ServiceOrBuilder>(
                  service_,
                  getParentForChildren(),
                  isClean());
          service_ = null;
        }
        return serviceBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:UARTMessage)
    }

    static {
      defaultInstance = new UARTMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:UARTMessage)
  }

  public interface ServiceOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .Service.ServiceType serviceType = 1;
    /**
     * <code>required .Service.ServiceType serviceType = 1;</code>
     */
    boolean hasServiceType();
    /**
     * <code>required .Service.ServiceType serviceType = 1;</code>
     */
    de.fhffm.ssns.messaging.UARTMessageProtos.Service.ServiceType getServiceType();

    // required uint32 serviceGroupId = 2;
    /**
     * <code>required uint32 serviceGroupId = 2;</code>
     */
    boolean hasServiceGroupId();
    /**
     * <code>required uint32 serviceGroupId = 2;</code>
     */
    int getServiceGroupId();

    // required uint32 serviceId = 3;
    /**
     * <code>required uint32 serviceId = 3;</code>
     */
    boolean hasServiceId();
    /**
     * <code>required uint32 serviceId = 3;</code>
     */
    int getServiceId();

    // optional uint32 value = 4;
    /**
     * <code>optional uint32 value = 4;</code>
     */
    boolean hasValue();
    /**
     * <code>optional uint32 value = 4;</code>
     */
    int getValue();

    // optional string info = 5;
    /**
     * <code>optional string info = 5;</code>
     */
    boolean hasInfo();
    /**
     * <code>optional string info = 5;</code>
     */
    java.lang.String getInfo();
    /**
     * <code>optional string info = 5;</code>
     */
    com.google.protobuf.ByteString
        getInfoBytes();
  }
  /**
   * Protobuf type {@code Service}
   */
  public static final class Service extends
      com.google.protobuf.GeneratedMessage
      implements ServiceOrBuilder {
    // Use Service.newBuilder() to construct.
    private Service(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Service(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Service defaultInstance;
    public static Service getDefaultInstance() {
      return defaultInstance;
    }

    public Service getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Service(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              de.fhffm.ssns.messaging.UARTMessageProtos.Service.ServiceType value = de.fhffm.ssns.messaging.UARTMessageProtos.Service.ServiceType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                serviceType_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              serviceGroupId_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              serviceId_ = input.readUInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              value_ = input.readUInt32();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              info_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.fhffm.ssns.messaging.UARTMessageProtos.internal_static_Service_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.fhffm.ssns.messaging.UARTMessageProtos.internal_static_Service_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.fhffm.ssns.messaging.UARTMessageProtos.Service.class, de.fhffm.ssns.messaging.UARTMessageProtos.Service.Builder.class);
    }

    public static com.google.protobuf.Parser<Service> PARSER =
        new com.google.protobuf.AbstractParser<Service>() {
      public Service parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Service(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Service> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code Service.ServiceType}
     */
    public enum ServiceType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ACTUATOR = 1;</code>
       */
      ACTUATOR(0, 1),
      /**
       * <code>SENSOR = 2;</code>
       */
      SENSOR(1, 2),
      ;

      /**
       * <code>ACTUATOR = 1;</code>
       */
      public static final int ACTUATOR_VALUE = 1;
      /**
       * <code>SENSOR = 2;</code>
       */
      public static final int SENSOR_VALUE = 2;


      public final int getNumber() { return value; }

      public static ServiceType valueOf(int value) {
        switch (value) {
          case 1: return ACTUATOR;
          case 2: return SENSOR;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ServiceType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ServiceType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ServiceType>() {
              public ServiceType findValueByNumber(int number) {
                return ServiceType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return de.fhffm.ssns.messaging.UARTMessageProtos.Service.getDescriptor().getEnumTypes().get(0);
      }

      private static final ServiceType[] VALUES = values();

      public static ServiceType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ServiceType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Service.ServiceType)
    }

    private int bitField0_;
    // required .Service.ServiceType serviceType = 1;
    public static final int SERVICETYPE_FIELD_NUMBER = 1;
    private de.fhffm.ssns.messaging.UARTMessageProtos.Service.ServiceType serviceType_;
    /**
     * <code>required .Service.ServiceType serviceType = 1;</code>
     */
    public boolean hasServiceType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .Service.ServiceType serviceType = 1;</code>
     */
    public de.fhffm.ssns.messaging.UARTMessageProtos.Service.ServiceType getServiceType() {
      return serviceType_;
    }

    // required uint32 serviceGroupId = 2;
    public static final int SERVICEGROUPID_FIELD_NUMBER = 2;
    private int serviceGroupId_;
    /**
     * <code>required uint32 serviceGroupId = 2;</code>
     */
    public boolean hasServiceGroupId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 serviceGroupId = 2;</code>
     */
    public int getServiceGroupId() {
      return serviceGroupId_;
    }

    // required uint32 serviceId = 3;
    public static final int SERVICEID_FIELD_NUMBER = 3;
    private int serviceId_;
    /**
     * <code>required uint32 serviceId = 3;</code>
     */
    public boolean hasServiceId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required uint32 serviceId = 3;</code>
     */
    public int getServiceId() {
      return serviceId_;
    }

    // optional uint32 value = 4;
    public static final int VALUE_FIELD_NUMBER = 4;
    private int value_;
    /**
     * <code>optional uint32 value = 4;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional uint32 value = 4;</code>
     */
    public int getValue() {
      return value_;
    }

    // optional string info = 5;
    public static final int INFO_FIELD_NUMBER = 5;
    private java.lang.Object info_;
    /**
     * <code>optional string info = 5;</code>
     */
    public boolean hasInfo() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string info = 5;</code>
     */
    public java.lang.String getInfo() {
      java.lang.Object ref = info_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          info_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string info = 5;</code>
     */
    public com.google.protobuf.ByteString
        getInfoBytes() {
      java.lang.Object ref = info_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        info_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      serviceType_ = de.fhffm.ssns.messaging.UARTMessageProtos.Service.ServiceType.ACTUATOR;
      serviceGroupId_ = 0;
      serviceId_ = 0;
      value_ = 0;
      info_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasServiceType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasServiceGroupId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasServiceId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, serviceType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, serviceGroupId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, serviceId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, value_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getInfoBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, serviceType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, serviceGroupId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, serviceId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, value_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getInfoBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static de.fhffm.ssns.messaging.UARTMessageProtos.Service parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.fhffm.ssns.messaging.UARTMessageProtos.Service parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.fhffm.ssns.messaging.UARTMessageProtos.Service parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.fhffm.ssns.messaging.UARTMessageProtos.Service parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.fhffm.ssns.messaging.UARTMessageProtos.Service parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.fhffm.ssns.messaging.UARTMessageProtos.Service parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static de.fhffm.ssns.messaging.UARTMessageProtos.Service parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static de.fhffm.ssns.messaging.UARTMessageProtos.Service parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static de.fhffm.ssns.messaging.UARTMessageProtos.Service parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.fhffm.ssns.messaging.UARTMessageProtos.Service parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.fhffm.ssns.messaging.UARTMessageProtos.Service prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Service}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements de.fhffm.ssns.messaging.UARTMessageProtos.ServiceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.fhffm.ssns.messaging.UARTMessageProtos.internal_static_Service_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.fhffm.ssns.messaging.UARTMessageProtos.internal_static_Service_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.fhffm.ssns.messaging.UARTMessageProtos.Service.class, de.fhffm.ssns.messaging.UARTMessageProtos.Service.Builder.class);
      }

      // Construct using de.fhffm.ssns.messaging.UARTMessageProtos.Service.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        serviceType_ = de.fhffm.ssns.messaging.UARTMessageProtos.Service.ServiceType.ACTUATOR;
        bitField0_ = (bitField0_ & ~0x00000001);
        serviceGroupId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        serviceId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        value_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        info_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.fhffm.ssns.messaging.UARTMessageProtos.internal_static_Service_descriptor;
      }

      public de.fhffm.ssns.messaging.UARTMessageProtos.Service getDefaultInstanceForType() {
        return de.fhffm.ssns.messaging.UARTMessageProtos.Service.getDefaultInstance();
      }

      public de.fhffm.ssns.messaging.UARTMessageProtos.Service build() {
        de.fhffm.ssns.messaging.UARTMessageProtos.Service result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.fhffm.ssns.messaging.UARTMessageProtos.Service buildPartial() {
        de.fhffm.ssns.messaging.UARTMessageProtos.Service result = new de.fhffm.ssns.messaging.UARTMessageProtos.Service(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serviceType_ = serviceType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.serviceGroupId_ = serviceGroupId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.serviceId_ = serviceId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.value_ = value_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.info_ = info_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.fhffm.ssns.messaging.UARTMessageProtos.Service) {
          return mergeFrom((de.fhffm.ssns.messaging.UARTMessageProtos.Service)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.fhffm.ssns.messaging.UARTMessageProtos.Service other) {
        if (other == de.fhffm.ssns.messaging.UARTMessageProtos.Service.getDefaultInstance()) return this;
        if (other.hasServiceType()) {
          setServiceType(other.getServiceType());
        }
        if (other.hasServiceGroupId()) {
          setServiceGroupId(other.getServiceGroupId());
        }
        if (other.hasServiceId()) {
          setServiceId(other.getServiceId());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        if (other.hasInfo()) {
          bitField0_ |= 0x00000010;
          info_ = other.info_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasServiceType()) {
          
          return false;
        }
        if (!hasServiceGroupId()) {
          
          return false;
        }
        if (!hasServiceId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.fhffm.ssns.messaging.UARTMessageProtos.Service parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.fhffm.ssns.messaging.UARTMessageProtos.Service) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .Service.ServiceType serviceType = 1;
      private de.fhffm.ssns.messaging.UARTMessageProtos.Service.ServiceType serviceType_ = de.fhffm.ssns.messaging.UARTMessageProtos.Service.ServiceType.ACTUATOR;
      /**
       * <code>required .Service.ServiceType serviceType = 1;</code>
       */
      public boolean hasServiceType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .Service.ServiceType serviceType = 1;</code>
       */
      public de.fhffm.ssns.messaging.UARTMessageProtos.Service.ServiceType getServiceType() {
        return serviceType_;
      }
      /**
       * <code>required .Service.ServiceType serviceType = 1;</code>
       */
      public Builder setServiceType(de.fhffm.ssns.messaging.UARTMessageProtos.Service.ServiceType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        serviceType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .Service.ServiceType serviceType = 1;</code>
       */
      public Builder clearServiceType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serviceType_ = de.fhffm.ssns.messaging.UARTMessageProtos.Service.ServiceType.ACTUATOR;
        onChanged();
        return this;
      }

      // required uint32 serviceGroupId = 2;
      private int serviceGroupId_ ;
      /**
       * <code>required uint32 serviceGroupId = 2;</code>
       */
      public boolean hasServiceGroupId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 serviceGroupId = 2;</code>
       */
      public int getServiceGroupId() {
        return serviceGroupId_;
      }
      /**
       * <code>required uint32 serviceGroupId = 2;</code>
       */
      public Builder setServiceGroupId(int value) {
        bitField0_ |= 0x00000002;
        serviceGroupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 serviceGroupId = 2;</code>
       */
      public Builder clearServiceGroupId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        serviceGroupId_ = 0;
        onChanged();
        return this;
      }

      // required uint32 serviceId = 3;
      private int serviceId_ ;
      /**
       * <code>required uint32 serviceId = 3;</code>
       */
      public boolean hasServiceId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required uint32 serviceId = 3;</code>
       */
      public int getServiceId() {
        return serviceId_;
      }
      /**
       * <code>required uint32 serviceId = 3;</code>
       */
      public Builder setServiceId(int value) {
        bitField0_ |= 0x00000004;
        serviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 serviceId = 3;</code>
       */
      public Builder clearServiceId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        serviceId_ = 0;
        onChanged();
        return this;
      }

      // optional uint32 value = 4;
      private int value_ ;
      /**
       * <code>optional uint32 value = 4;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional uint32 value = 4;</code>
       */
      public int getValue() {
        return value_;
      }
      /**
       * <code>optional uint32 value = 4;</code>
       */
      public Builder setValue(int value) {
        bitField0_ |= 0x00000008;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 value = 4;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000008);
        value_ = 0;
        onChanged();
        return this;
      }

      // optional string info = 5;
      private java.lang.Object info_ = "";
      /**
       * <code>optional string info = 5;</code>
       */
      public boolean hasInfo() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string info = 5;</code>
       */
      public java.lang.String getInfo() {
        java.lang.Object ref = info_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          info_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string info = 5;</code>
       */
      public com.google.protobuf.ByteString
          getInfoBytes() {
        java.lang.Object ref = info_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          info_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string info = 5;</code>
       */
      public Builder setInfo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        info_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string info = 5;</code>
       */
      public Builder clearInfo() {
        bitField0_ = (bitField0_ & ~0x00000010);
        info_ = getDefaultInstance().getInfo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string info = 5;</code>
       */
      public Builder setInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        info_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Service)
    }

    static {
      defaultInstance = new Service(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Service)
  }

  public interface BeaconOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required uint32 serviceGroupId = 1;
    /**
     * <code>required uint32 serviceGroupId = 1;</code>
     */
    boolean hasServiceGroupId();
    /**
     * <code>required uint32 serviceGroupId = 1;</code>
     */
    int getServiceGroupId();

    // optional string name = 2;
    /**
     * <code>optional string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // repeated .Service service = 3;
    /**
     * <code>repeated .Service service = 3;</code>
     */
    java.util.List<de.fhffm.ssns.messaging.UARTMessageProtos.Service> 
        getServiceList();
    /**
     * <code>repeated .Service service = 3;</code>
     */
    de.fhffm.ssns.messaging.UARTMessageProtos.Service getService(int index);
    /**
     * <code>repeated .Service service = 3;</code>
     */
    int getServiceCount();
    /**
     * <code>repeated .Service service = 3;</code>
     */
    java.util.List<? extends de.fhffm.ssns.messaging.UARTMessageProtos.ServiceOrBuilder> 
        getServiceOrBuilderList();
    /**
     * <code>repeated .Service service = 3;</code>
     */
    de.fhffm.ssns.messaging.UARTMessageProtos.ServiceOrBuilder getServiceOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Beacon}
   */
  public static final class Beacon extends
      com.google.protobuf.GeneratedMessage
      implements BeaconOrBuilder {
    // Use Beacon.newBuilder() to construct.
    private Beacon(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Beacon(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Beacon defaultInstance;
    public static Beacon getDefaultInstance() {
      return defaultInstance;
    }

    public Beacon getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Beacon(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              serviceGroupId_ = input.readUInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                service_ = new java.util.ArrayList<de.fhffm.ssns.messaging.UARTMessageProtos.Service>();
                mutable_bitField0_ |= 0x00000004;
              }
              service_.add(input.readMessage(de.fhffm.ssns.messaging.UARTMessageProtos.Service.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          service_ = java.util.Collections.unmodifiableList(service_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.fhffm.ssns.messaging.UARTMessageProtos.internal_static_Beacon_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.fhffm.ssns.messaging.UARTMessageProtos.internal_static_Beacon_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.fhffm.ssns.messaging.UARTMessageProtos.Beacon.class, de.fhffm.ssns.messaging.UARTMessageProtos.Beacon.Builder.class);
    }

    public static com.google.protobuf.Parser<Beacon> PARSER =
        new com.google.protobuf.AbstractParser<Beacon>() {
      public Beacon parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Beacon(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Beacon> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required uint32 serviceGroupId = 1;
    public static final int SERVICEGROUPID_FIELD_NUMBER = 1;
    private int serviceGroupId_;
    /**
     * <code>required uint32 serviceGroupId = 1;</code>
     */
    public boolean hasServiceGroupId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 serviceGroupId = 1;</code>
     */
    public int getServiceGroupId() {
      return serviceGroupId_;
    }

    // optional string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .Service service = 3;
    public static final int SERVICE_FIELD_NUMBER = 3;
    private java.util.List<de.fhffm.ssns.messaging.UARTMessageProtos.Service> service_;
    /**
     * <code>repeated .Service service = 3;</code>
     */
    public java.util.List<de.fhffm.ssns.messaging.UARTMessageProtos.Service> getServiceList() {
      return service_;
    }
    /**
     * <code>repeated .Service service = 3;</code>
     */
    public java.util.List<? extends de.fhffm.ssns.messaging.UARTMessageProtos.ServiceOrBuilder> 
        getServiceOrBuilderList() {
      return service_;
    }
    /**
     * <code>repeated .Service service = 3;</code>
     */
    public int getServiceCount() {
      return service_.size();
    }
    /**
     * <code>repeated .Service service = 3;</code>
     */
    public de.fhffm.ssns.messaging.UARTMessageProtos.Service getService(int index) {
      return service_.get(index);
    }
    /**
     * <code>repeated .Service service = 3;</code>
     */
    public de.fhffm.ssns.messaging.UARTMessageProtos.ServiceOrBuilder getServiceOrBuilder(
        int index) {
      return service_.get(index);
    }

    private void initFields() {
      serviceGroupId_ = 0;
      name_ = "";
      service_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasServiceGroupId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getServiceCount(); i++) {
        if (!getService(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, serviceGroupId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      for (int i = 0; i < service_.size(); i++) {
        output.writeMessage(3, service_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, serviceGroupId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      for (int i = 0; i < service_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, service_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static de.fhffm.ssns.messaging.UARTMessageProtos.Beacon parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.fhffm.ssns.messaging.UARTMessageProtos.Beacon parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.fhffm.ssns.messaging.UARTMessageProtos.Beacon parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.fhffm.ssns.messaging.UARTMessageProtos.Beacon parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.fhffm.ssns.messaging.UARTMessageProtos.Beacon parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.fhffm.ssns.messaging.UARTMessageProtos.Beacon parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static de.fhffm.ssns.messaging.UARTMessageProtos.Beacon parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static de.fhffm.ssns.messaging.UARTMessageProtos.Beacon parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static de.fhffm.ssns.messaging.UARTMessageProtos.Beacon parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.fhffm.ssns.messaging.UARTMessageProtos.Beacon parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.fhffm.ssns.messaging.UARTMessageProtos.Beacon prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Beacon}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements de.fhffm.ssns.messaging.UARTMessageProtos.BeaconOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.fhffm.ssns.messaging.UARTMessageProtos.internal_static_Beacon_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.fhffm.ssns.messaging.UARTMessageProtos.internal_static_Beacon_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.fhffm.ssns.messaging.UARTMessageProtos.Beacon.class, de.fhffm.ssns.messaging.UARTMessageProtos.Beacon.Builder.class);
      }

      // Construct using de.fhffm.ssns.messaging.UARTMessageProtos.Beacon.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getServiceFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        serviceGroupId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (serviceBuilder_ == null) {
          service_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          serviceBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.fhffm.ssns.messaging.UARTMessageProtos.internal_static_Beacon_descriptor;
      }

      public de.fhffm.ssns.messaging.UARTMessageProtos.Beacon getDefaultInstanceForType() {
        return de.fhffm.ssns.messaging.UARTMessageProtos.Beacon.getDefaultInstance();
      }

      public de.fhffm.ssns.messaging.UARTMessageProtos.Beacon build() {
        de.fhffm.ssns.messaging.UARTMessageProtos.Beacon result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.fhffm.ssns.messaging.UARTMessageProtos.Beacon buildPartial() {
        de.fhffm.ssns.messaging.UARTMessageProtos.Beacon result = new de.fhffm.ssns.messaging.UARTMessageProtos.Beacon(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serviceGroupId_ = serviceGroupId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (serviceBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            service_ = java.util.Collections.unmodifiableList(service_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.service_ = service_;
        } else {
          result.service_ = serviceBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.fhffm.ssns.messaging.UARTMessageProtos.Beacon) {
          return mergeFrom((de.fhffm.ssns.messaging.UARTMessageProtos.Beacon)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.fhffm.ssns.messaging.UARTMessageProtos.Beacon other) {
        if (other == de.fhffm.ssns.messaging.UARTMessageProtos.Beacon.getDefaultInstance()) return this;
        if (other.hasServiceGroupId()) {
          setServiceGroupId(other.getServiceGroupId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (serviceBuilder_ == null) {
          if (!other.service_.isEmpty()) {
            if (service_.isEmpty()) {
              service_ = other.service_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureServiceIsMutable();
              service_.addAll(other.service_);
            }
            onChanged();
          }
        } else {
          if (!other.service_.isEmpty()) {
            if (serviceBuilder_.isEmpty()) {
              serviceBuilder_.dispose();
              serviceBuilder_ = null;
              service_ = other.service_;
              bitField0_ = (bitField0_ & ~0x00000004);
              serviceBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getServiceFieldBuilder() : null;
            } else {
              serviceBuilder_.addAllMessages(other.service_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasServiceGroupId()) {
          
          return false;
        }
        for (int i = 0; i < getServiceCount(); i++) {
          if (!getService(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.fhffm.ssns.messaging.UARTMessageProtos.Beacon parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.fhffm.ssns.messaging.UARTMessageProtos.Beacon) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint32 serviceGroupId = 1;
      private int serviceGroupId_ ;
      /**
       * <code>required uint32 serviceGroupId = 1;</code>
       */
      public boolean hasServiceGroupId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 serviceGroupId = 1;</code>
       */
      public int getServiceGroupId() {
        return serviceGroupId_;
      }
      /**
       * <code>required uint32 serviceGroupId = 1;</code>
       */
      public Builder setServiceGroupId(int value) {
        bitField0_ |= 0x00000001;
        serviceGroupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 serviceGroupId = 1;</code>
       */
      public Builder clearServiceGroupId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serviceGroupId_ = 0;
        onChanged();
        return this;
      }

      // optional string name = 2;
      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      // repeated .Service service = 3;
      private java.util.List<de.fhffm.ssns.messaging.UARTMessageProtos.Service> service_ =
        java.util.Collections.emptyList();
      private void ensureServiceIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          service_ = new java.util.ArrayList<de.fhffm.ssns.messaging.UARTMessageProtos.Service>(service_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          de.fhffm.ssns.messaging.UARTMessageProtos.Service, de.fhffm.ssns.messaging.UARTMessageProtos.Service.Builder, de.fhffm.ssns.messaging.UARTMessageProtos.ServiceOrBuilder> serviceBuilder_;

      /**
       * <code>repeated .Service service = 3;</code>
       */
      public java.util.List<de.fhffm.ssns.messaging.UARTMessageProtos.Service> getServiceList() {
        if (serviceBuilder_ == null) {
          return java.util.Collections.unmodifiableList(service_);
        } else {
          return serviceBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Service service = 3;</code>
       */
      public int getServiceCount() {
        if (serviceBuilder_ == null) {
          return service_.size();
        } else {
          return serviceBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Service service = 3;</code>
       */
      public de.fhffm.ssns.messaging.UARTMessageProtos.Service getService(int index) {
        if (serviceBuilder_ == null) {
          return service_.get(index);
        } else {
          return serviceBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Service service = 3;</code>
       */
      public Builder setService(
          int index, de.fhffm.ssns.messaging.UARTMessageProtos.Service value) {
        if (serviceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureServiceIsMutable();
          service_.set(index, value);
          onChanged();
        } else {
          serviceBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Service service = 3;</code>
       */
      public Builder setService(
          int index, de.fhffm.ssns.messaging.UARTMessageProtos.Service.Builder builderForValue) {
        if (serviceBuilder_ == null) {
          ensureServiceIsMutable();
          service_.set(index, builderForValue.build());
          onChanged();
        } else {
          serviceBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Service service = 3;</code>
       */
      public Builder addService(de.fhffm.ssns.messaging.UARTMessageProtos.Service value) {
        if (serviceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureServiceIsMutable();
          service_.add(value);
          onChanged();
        } else {
          serviceBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Service service = 3;</code>
       */
      public Builder addService(
          int index, de.fhffm.ssns.messaging.UARTMessageProtos.Service value) {
        if (serviceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureServiceIsMutable();
          service_.add(index, value);
          onChanged();
        } else {
          serviceBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Service service = 3;</code>
       */
      public Builder addService(
          de.fhffm.ssns.messaging.UARTMessageProtos.Service.Builder builderForValue) {
        if (serviceBuilder_ == null) {
          ensureServiceIsMutable();
          service_.add(builderForValue.build());
          onChanged();
        } else {
          serviceBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Service service = 3;</code>
       */
      public Builder addService(
          int index, de.fhffm.ssns.messaging.UARTMessageProtos.Service.Builder builderForValue) {
        if (serviceBuilder_ == null) {
          ensureServiceIsMutable();
          service_.add(index, builderForValue.build());
          onChanged();
        } else {
          serviceBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Service service = 3;</code>
       */
      public Builder addAllService(
          java.lang.Iterable<? extends de.fhffm.ssns.messaging.UARTMessageProtos.Service> values) {
        if (serviceBuilder_ == null) {
          ensureServiceIsMutable();
          super.addAll(values, service_);
          onChanged();
        } else {
          serviceBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Service service = 3;</code>
       */
      public Builder clearService() {
        if (serviceBuilder_ == null) {
          service_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          serviceBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Service service = 3;</code>
       */
      public Builder removeService(int index) {
        if (serviceBuilder_ == null) {
          ensureServiceIsMutable();
          service_.remove(index);
          onChanged();
        } else {
          serviceBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Service service = 3;</code>
       */
      public de.fhffm.ssns.messaging.UARTMessageProtos.Service.Builder getServiceBuilder(
          int index) {
        return getServiceFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Service service = 3;</code>
       */
      public de.fhffm.ssns.messaging.UARTMessageProtos.ServiceOrBuilder getServiceOrBuilder(
          int index) {
        if (serviceBuilder_ == null) {
          return service_.get(index);  } else {
          return serviceBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Service service = 3;</code>
       */
      public java.util.List<? extends de.fhffm.ssns.messaging.UARTMessageProtos.ServiceOrBuilder> 
           getServiceOrBuilderList() {
        if (serviceBuilder_ != null) {
          return serviceBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(service_);
        }
      }
      /**
       * <code>repeated .Service service = 3;</code>
       */
      public de.fhffm.ssns.messaging.UARTMessageProtos.Service.Builder addServiceBuilder() {
        return getServiceFieldBuilder().addBuilder(
            de.fhffm.ssns.messaging.UARTMessageProtos.Service.getDefaultInstance());
      }
      /**
       * <code>repeated .Service service = 3;</code>
       */
      public de.fhffm.ssns.messaging.UARTMessageProtos.Service.Builder addServiceBuilder(
          int index) {
        return getServiceFieldBuilder().addBuilder(
            index, de.fhffm.ssns.messaging.UARTMessageProtos.Service.getDefaultInstance());
      }
      /**
       * <code>repeated .Service service = 3;</code>
       */
      public java.util.List<de.fhffm.ssns.messaging.UARTMessageProtos.Service.Builder> 
           getServiceBuilderList() {
        return getServiceFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          de.fhffm.ssns.messaging.UARTMessageProtos.Service, de.fhffm.ssns.messaging.UARTMessageProtos.Service.Builder, de.fhffm.ssns.messaging.UARTMessageProtos.ServiceOrBuilder> 
          getServiceFieldBuilder() {
        if (serviceBuilder_ == null) {
          serviceBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              de.fhffm.ssns.messaging.UARTMessageProtos.Service, de.fhffm.ssns.messaging.UARTMessageProtos.Service.Builder, de.fhffm.ssns.messaging.UARTMessageProtos.ServiceOrBuilder>(
                  service_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          service_ = null;
        }
        return serviceBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Beacon)
    }

    static {
      defaultInstance = new Beacon(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Beacon)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_UARTMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UARTMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Service_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Service_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Beacon_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Beacon_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021uartmessage.proto\"\203\001\n\013UARTMessage\022\037\n\004t" +
      "ype\030\001 \002(\0162\021.UARTMessage.Type\022\027\n\006beacon\030\002" +
      " \001(\0132\007.Beacon\022\031\n\007service\030\003 \001(\0132\010.Service" +
      "\"\037\n\004Type\022\013\n\007SERVICE\020\001\022\n\n\006BEACON\020\002\"\245\001\n\007Se" +
      "rvice\022)\n\013serviceType\030\001 \002(\0162\024.Service.Ser" +
      "viceType\022\026\n\016serviceGroupId\030\002 \002(\r\022\021\n\tserv" +
      "iceId\030\003 \002(\r\022\r\n\005value\030\004 \001(\r\022\014\n\004info\030\005 \001(\t" +
      "\"\'\n\013ServiceType\022\014\n\010ACTUATOR\020\001\022\n\n\006SENSOR\020" +
      "\002\"I\n\006Beacon\022\026\n\016serviceGroupId\030\001 \002(\r\022\014\n\004n" +
      "ame\030\002 \001(\t\022\031\n\007service\030\003 \003(\0132\010.ServiceB,\n\027",
      "de.fhffm.ssns.messagingB\021UARTMessageProt" +
      "os"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_UARTMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_UARTMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_UARTMessage_descriptor,
              new java.lang.String[] { "Type", "Beacon", "Service", });
          internal_static_Service_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Service_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Service_descriptor,
              new java.lang.String[] { "ServiceType", "ServiceGroupId", "ServiceId", "Value", "Info", });
          internal_static_Beacon_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_Beacon_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Beacon_descriptor,
              new java.lang.String[] { "ServiceGroupId", "Name", "Service", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
