/* Automatically generated nanopb header */
/* Generated by nanopb-0.2.7 at Wed May 07 17:51:04 2014. */

#ifndef _PB_UARTMESSAGE_PB_H_
#define _PB_UARTMESSAGE_PB_H_
#include <pb.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _UARTMessage_Type {
    UARTMessage_Type_SERVICE = 1,
    UARTMessage_Type_BEACON = 3
} UARTMessage_Type;

typedef enum _Service_ServiceType {
    Service_ServiceType_ACTUATOR = 1,
    Service_ServiceType_SENSOR = 2
} Service_ServiceType;

/* Struct definitions */
typedef struct _Service {
    Service_ServiceType serviceType;
    uint32_t serviceGroup;
    uint32_t serviceId;
    bool has_value;
    uint32_t value;
    pb_callback_t info;
} Service;

typedef struct _ServiceGroup {
    uint32_t id;
    pb_callback_t name;
    pb_callback_t service;
} ServiceGroup;

typedef struct _Beacon {
    pb_callback_t serviceGroup;
} Beacon;

typedef struct _UARTMessage {
    UARTMessage_Type type;
    bool has_beacon;
    Beacon beacon;
    bool has_services;
    Service services;
} UARTMessage;

/* Default values for struct fields */

/* Field tags (for use in manual encoding/decoding) */
#define Service_serviceType_tag                  1
#define Service_serviceGroup_tag                 2
#define Service_serviceId_tag                    3
#define Service_value_tag                        4
#define Service_info_tag                         5
#define ServiceGroup_id_tag                      1
#define ServiceGroup_name_tag                    2
#define ServiceGroup_service_tag                 3
#define Beacon_serviceGroup_tag                  1
#define UARTMessage_type_tag                     1
#define UARTMessage_beacon_tag                   2
#define UARTMessage_services_tag                 3

/* Struct field encoding specification for nanopb */
extern const pb_field_t UARTMessage_fields[4];
extern const pb_field_t Service_fields[6];
extern const pb_field_t Beacon_fields[2];
extern const pb_field_t ServiceGroup_fields[4];

/* Maximum encoded size of messages (where known) */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
